# Generated by Django 4.1.4 on 2022-12-24 12:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import modelcluster.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(max_length=255, unique=True, verbose_name='Tracking ID')),
                ('shipped_from', django_countries.fields.CountryField(max_length=2, verbose_name='Shipping From')),
                ('shipped_to', django_countries.fields.CountryField(max_length=2, verbose_name='Shipping To')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Is Delivered?')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('LOST', 'Lost'), ('RETURNED', 'Returned'), ('ON_HOLD', 'On Hold')], default='IN_TRANSIT', max_length=255, verbose_name='Shipping Status')),
                ('type', models.CharField(choices=[('EXPRESS', 'Express'), ('PRIORITY', 'Priority'), ('STANDARD', 'Standard'), ('OTHER', 'Other')], default='STANDARD', max_length=255, verbose_name='Shipping Type')),
                ('mode', models.CharField(choices=[('AIR', 'Air'), ('LAND', 'Land'), ('SEA', 'Sea'), ('TRAIN', 'Train')], default='LAND', max_length=255, verbose_name='Shipping Mode')),
                ('exp_delivery', models.DateField(verbose_name='Expected Delivery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.CharField(max_length=255, verbose_name='Context')),
                ('time_updated', models.DateTimeField(verbose_name='Time Updated')),
                ('order', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='btl_logistics.order')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
